version: "3"

services:
    postgres:
        image: postgres
        container_name: backend-postgres
        environment:
            POSTGRES_PASSWORD: backend
            POSTGRES_USER: root
            POSTGRES_DB: backendapp
        ports:
            - "5432:5432"
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
